Add VictorOps alert notification capability
HBOCodeLabs/grafana pull request #1
Opened 2016-10-27 19:52 UTC by ichekrygin

###Overview

VictorOps is a hub for centralizing the flow of information throughout the incident lifecycle. Driven by IT and DevOps system data, VictorOps provides a unified platform for real-time alerting, collaboration, and documentation (https://victorops.com/)

This PR adds functionality to `POST` alert notifications to VictorOps via [REST API](http://victorops.force.com/knowledgebase/articles/Integration/Alert-Ingestion-API-Documentation/)

2016-10-27 20:12 UTC, dcarney requested changes

2016-10-27 20:12 UTC, dcarney commented on pkg/services/alerting/notifiers/victorops.go
> +	m "github.com/grafana/grafana/pkg/models"
nit: I know import aliases can be helpful, but in this case I think aliasing "models" to "m" is a little excessive.

2016-10-27 20:12 UTC, dcarney commented on pkg/services/alerting/notifiers/victorops.go
> +		return nil, alerting.ValidationError{Reason: "Could not find url property in settings"}
nit: maybe make this say "Could not find victorops url property in settings"?

2016-10-27 20:12 UTC, dcarney commented on pkg/services/alerting/notifiers/victorops.go
> +func NewVictoropsNotifier(model *m.AlertNotification) (alerting.Notifier, error) {
Should include some godoc for this function, since it's exported.

2016-10-27 20:12 UTC, dcarney commented on pkg/services/alerting/notifiers/victorops.go
> +	data, _ := json.Marshal(&body)
You're ignoring/swallowing an error here.

2016-10-27 20:12 UTC, dcarney commented on pkg/services/alerting/notifiers/victorops.go
> +    "timestamp": time.Now().Unix(),
Does VO use nanoseconds for it's timestamps?  That's surprising to me.  If it's epoch milliseconds instead, you can use:

```
time.Now().Unix() / 1e6
```

2016-10-27 20:31 UTC, zihaoyu commented on public/app/features/alerting/alert_tab_ctrl.ts
> +      case "victorops": return "fa fa-victorops";
Does Font Awesome have a VO icon? I don't see it in the [list](http://fontawesome.io/icons/).

2016-10-27 20:34 UTC, dcarney approved these changes
A few findings from `golint`:

```
notifiers/victorops.go:15:7: exported const AlertStateCritical should have comment or be unexported
notifiers/victorops.go:36:6: exported type VictoropsNotifier should have comment or be unexported
notifiers/victorops.go:38:2: struct field Url should be URL
notifiers/victorops.go:42:1: exported method VictoropsNotifier.Notify should have comment or be unexported
notifiers/victorops.go:42:1: receiver name should be a reflection of its identity; don't use generic names such as "this" or "self"
```

I know that other parts of the grafana codebase probably throw similar warnings (especially the last one, about using `this` as a receiver name), so it's up to you as to whether you want to:
- match the conventions of the rest of grafana
- please the linter

I _do_ think that you could add some godoc to the VictoropsNotifier typedef though.  It might seem like overkill, but it's a good habit.

2016-10-27 20:35 UTC, dcarney commented on public/app/features/alerting/alert_tab_ctrl.ts
> +      case "victorops": return "fa fa-victorops";
I was wondering what "fa" was referring to.  :-)

2016-10-27 20:39 UTC, jlutzhbo commented on pkg/services/alerting/notifiers/victorops.go
> +		"message_type":     messageType,
why is this indentation 2 spaces? Golang indentation should be 2 tabs!

2016-10-27 20:40 UTC, ichekrygin commented on public/app/features/alerting/alert_tab_ctrl.ts
> +      case "victorops": return "fa fa-victorops";
I didn't even know what that was either just C&P&R

2016-10-27 20:41 UTC, ichekrygin commented on pkg/services/alerting/notifiers/victorops.go
> +		"message_type":     messageType,
eh.. not sure, this is after running `go fmt` on it.

2016-10-27 20:46 UTC, ichekrygin commented on pkg/services/alerting/notifiers/victorops.go
> +		"message_type":     messageType,
@jlutzhbo I just re-run `go fmt` once again, which didn't yield any changes

2016-10-27 20:57 UTC, dcarney commented on pkg/services/alerting/notifiers/victorops.go
> +// VictoropsNotifier defines ULR property for Victorops REST API
typo: "ULR"

2016-10-27 20:58 UTC, dcarney commented
Made _one last_ comment about a typo.  Sorry.  :-)

2016-10-27 20:58 UTC, dcarney commented
LGTM otherwise.

2016-10-28 00:07 UTC, zihaoyu commented on pkg/services/alerting/notifiers/victorops.go
> +		"message_type":     messageType,
This looks normal to me.

2016-10-28 00:08 UTC, zihaoyu commented on public/app/features/alerting/partials/notification_edit.html
> +      <h3 class="page-heading">Victorops settings</h3>
I think for user-facing text, we should use VO's name correctly, VictorOps, capital V and O.

2016-10-28 00:09 UTC, zihaoyu commented
One comment about the VO name in user-facing text, besides that GTG

2016-10-30 18:17 UTC, ichekrygin commented
Added additional feature: alert on ExecutionError. This will allow us to suppress alerts triggered by `Grafana`'s failures to execute queries against TSDB's

![image](https://cloud.githubusercontent.com/assets/324803/19838714/383afdee-9e92-11e6-832c-6802a0a76265.png)

2016-10-31 14:11 UTC, zihaoyu commented
LGTM

2016-11-01 21:52 UTC, dcarney commented
Did you `gofmt` everything?  ;-)

2016-11-01 21:53 UTC, dcarney commented
Do you have to provide explanatory text to explain what "Alert on Exec Error" is?  I don't see anything like that in here, but I'm assuming that something should show up when you hover over the "i" icon in the GUI.

2016-11-01 21:54 UTC, dcarney commented
Few comments ☝️ , LGTM otherwise.

2016-11-01 21:59 UTC, ichekrygin commented
@dcarney: i think i did `go fmt` do you see any issues?

2016-11-01 22:00 UTC, ichekrygin commented
@dcarney: `tooltip="Trigger incident on Execution Error"`

2016-11-16 19:32 UTC, closed without merging